// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MinesweeperApi.Models;

namespace MinesweeperApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20190524123703_NewFieldsInBoard")]
    partial class NewFieldsInBoard
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MinesweeperApi.Models.GameBoard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("DateCreated");

                    b.Property<int>("Height");

                    b.Property<int>("MineCount");

                    b.Property<string>("Name");

                    b.Property<int>("Status");

                    b.Property<int>("Width");

                    b.HasKey("Id");

                    b.ToTable("GameBoards");
                });

            modelBuilder.Entity("MinesweeperApi.Models.Panel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AdjacentMines");

                    b.Property<int?>("GameBoardId");

                    b.Property<bool>("IsFlagged");

                    b.Property<bool>("IsMine");

                    b.Property<bool>("IsRevealed");

                    b.Property<int>("X");

                    b.Property<int>("Y");

                    b.HasKey("Id");

                    b.HasIndex("GameBoardId");

                    b.ToTable("Panel");
                });

            modelBuilder.Entity("MinesweeperApi.Models.Panel", b =>
                {
                    b.HasOne("MinesweeperApi.Models.GameBoard")
                        .WithMany("Panels")
                        .HasForeignKey("GameBoardId");
                });
#pragma warning restore 612, 618
        }
    }
}
